// console.log('Hello from ts');
var myString;
var mySlicedString;
var myNum;
var myBool;
var myVar;
// Note that these expected type syntaxes are the same
//let strArr: string[];
var strArr;
//let numArr: number[];
var numArr;
//let boolArr: boolean[];
var boolArr;
var strNumTuple;
// let myVoid: void = null;
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
myString = 'Hello' + ' ' + 'World';
mySlicedString = 'Hello'.slice(0, 3);
myNum = 0xf00d;
myBool = false;
myVar = 'Hello';
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['Hello', 4, 2, 1, 5];
console.log('myString: ' + myString);
console.log('mySlicedString: ' + mySlicedString);
console.log('myNum: ' + myNum);
console.log('myBool: ' + myBool);
console.log('myVar: ' + myVar);
console.log(strArr);
console.log(numArr);
console.log(boolArr);
console.log(strNumTuple);
console.log(myVoid);
